/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.vkeyboard_service;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class raw {
        public static final int adbkey=0x7f040000;
        public static final int start=0x7f040001;
        public static final int stop=0x7f040002;
        public static final int voicedata=0x7f040003;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
}
